### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by SeloSlav** [vgrec/SimpleRssReader#2]
I get this exception when running your code as per your blog post: https://androidresearch.wordpress.com/2013/06/01/creating-a-simple-rss-application-in-android-v2/

 java.lang.ClassCastException: android.support.v4.os.ResultReceiver cannot be cast to android.os.ResultReceiver
                                                                        at com.yitter.android.RssService.onHandleIntent(RssService.java:45)
                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

I'm not sure what to do about this...

**Comment by vgrec** [comment]
Check your imports.

In one place you are using ResultReceiver from the support library: android.support.v4.os.ResultReceiver, and in the other place from the framework: android.os.ResultReceiver.

Have both imports of the same type, eg.: both in the RssFragment and in the RssService:
import android.os.ResultReceiver;
